FROM postgres:16.2-alpine

# RUN rm -r /var/log/postgresql
# RUN mkdir /var/log/postgresql
# RUN chown postgres:postgres /var/log/postgresql

# CMD postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs